// Bridges the env type returned by @opennextjs/cloudflare's
// getCloudflareContext() to the bindings generated by `wrangler types` into the
// global `Env` (worker-configuration.d.ts). Regenerate types with
// `npm run cf-typegen` after changing wrangler.jsonc.
declare global {
  interface CloudflareEnv extends Env {}
}

export {};
