// Custom Worker entry. It re-exports the EventHub Durable Object and routes the
// real-time SSE endpoint (/api/events) straight to it, while delegating every
// other request to the Next.js app produced by @opennextjs/cloudflare.
//
// `./.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
// @ts-ignore generated at build time
import { default as handler } from "./.open-next/worker.js";

import { EventHub } from "./src/server/eventHub";

// `Env` is the wrangler-generated binding type (worker-configuration.d.ts,
// regenerated by `npm run cf-typegen`) — no hand-written parallel interface.
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/api/events") {
      const stub = env.EVENT_HUB.get(env.EVENT_HUB.idFromName("global"));
      return stub.fetch(request);
    }
    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;

export { EventHub };
