// Worker entry: the whole server. Routes the real-time SSE endpoint to the
// EventHub Durable Object, the billable AI/TTS routes to their handlers, and
// serves the Vite-built SPA (dist/) for everything else.
import { EventHub } from "./src/server/eventHub";
import { handleAiChat, handleAiDecision, handleTts } from "./src/server/routes";

// `Env` is the wrangler-generated binding type (worker-configuration.d.ts,
// regenerated by `npm run cf-typegen`) — no hand-written parallel interface.
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/api/events") {
      const stub = env.EVENT_HUB.get(env.EVENT_HUB.idFromName("global"));
      return stub.fetch(request);
    }

    if (request.method === "POST") {
      if (url.pathname === "/api/ai/decision")
        return handleAiDecision(request, env);
      if (url.pathname === "/api/ai/chat") return handleAiChat(request, env);
      if (url.pathname === "/api/tts") return handleTts(request);
    }

    void ctx;
    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;

export { EventHub };
